# Generated by Django 3.1.3 on 2020-12-05 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201205_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='timeStamp',
        ),
    ]
