# Generated by Django 3.1.3 on 2020-12-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_about_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='timeStamp',
            field=models.DateTimeField(auto_now_add=True, default=('2020-12-04', '11:34:49')),
            preserve_default=False,
        ),
    ]
