# Generated by Django 3.1.3 on 2020-12-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_about_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='timeStamp',
        ),
    ]
